# -*- coding: utf-8 -*-
"""Untitled45.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-sxiqa_AmlKQqKjXb4WoQDtZwHcJotsf
"""

from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas

def create_sample_pdf(filename="enterprise_contract.pdf"):
    c = canvas.Canvas(filename, pagesize=letter)

    # Page 1: General Terms & Data Compliance
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, 750, "MASTER SERVICES AGREEMENT - CONFIDENTIAL")
    c.setFont("Helvetica", 10)
    c.drawString(50, 720, "Clause 1.1: Scope of Work - The Vendor agrees to maintain enterprise cloud infrastructure.")
    c.drawString(50, 700, "Clause 2.3 (Data Security & GDPR): All European customer records must be stored within EU borders.")
    c.drawString(50, 680, "Cross-border data transfer without explicit written approval incurs a statutory compliance penalty of $250,000.")
    c.showPage()

    # Page 2: SLAs and Downtime Penalties
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, 750, "SECTION 4: SERVICE LEVEL AGREEMENT (SLA) & PENALTIES")
    c.setFont("Helvetica", 10)
    c.drawString(50, 720, "Clause 4.1: Uptime Commitment - Vendor guarantees a minimum monthly uptime of 99.9%.")
    c.drawString(50, 700, "Clause 4.2 (Downtime Penalty Formula): For every 1 hour of unapproved server outage exceeding 0.1%,")
    c.drawString(50, 680, "the vendor shall be liable to pay a penalty of $50,000 per incident.")
    c.drawString(50, 660, "Clause 5.1: Termination Notice - Either party can terminate with a 60-day prior written notice.")
    c.showPage()
    c.save()

create_sample_pdf()
print("Sample Enterprise Contract PDF Generated!")

from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_community.vectorstores import Chroma
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.retrievers import BM25Retriever

# 1. PDF Load karna
loader = PyPDFLoader("enterprise_contract.pdf")
docs = loader.load()

# 2. Text Chunks banana
text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=400,
    chunk_overlap=50
)
chunks = text_splitter.split_documents(docs)

# 3. Dense Vector DB (ChromaDB + Local Embedding)
embeddings = HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")
vectorstore = Chroma.from_documents(chunks, embeddings)
chroma_retriever = vectorstore.as_retriever(search_kwargs={"k": 2})

# 4. Sparse Keyword Search (BM25)
bm25_retriever = BM25Retriever.from_documents(chunks)
bm25_retriever.k = 2

# 5. Clean Custom Hybrid Engine (Dense + Sparse with Deduplication)
class EnterpriseHybridRetriever:
    def __init__(self, bm25, chroma):
        self.bm25 = bm25
        self.chroma = chroma

    def invoke(self, query: str):
        dense_docs = self.chroma.invoke(query)
        sparse_docs = self.bm25.invoke(query)

        # Combine results and remove duplicates
        seen = set()
        unique_docs = []
        for doc in dense_docs + sparse_docs:
            if doc.page_content not in seen:
                seen.add(doc.page_content)
                unique_docs.append(doc)
        return unique_docs[:3]

hybrid_retriever = EnterpriseHybridRetriever(bm25_retriever, chroma_retriever)

print(f"✅ Success! Ingested {len(chunks)} chunks into Hybrid Retrieval Engine.")

import os
import streamlit as st
from langchain_groq import ChatGroq
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser

# Cloud-safe API Key fetching
groq_api_key = st.secrets.get("GROQ_API_KEY") or os.environ.get("GROQ_API_KEY") or "gsk_your_actual_groq_key_here"
os.environ["GROQ_API_KEY"] = groq_api_key

# Ultra-fast open-source LLM
llm = ChatGroq(
    model_name="llama-3.3-70b-versatile",
    temperature=0.0
)

# Strict Legal Auditor Prompt (Zero-Hallucination Guardrail)
audit_prompt = PromptTemplate.from_template("""
You are a Senior Enterprise Legal & Compliance Auditor.
Analyze and answer the user's question STRICTLY using the context provided below.

[CONTEXT]:
{context}

[USER QUESTION]:
{question}

Mandatory Compliance Rules:
1. State the exact finding clearly in structured bullet points.
2. ALWAYS cite the exact Page Number and Clause Number if found in context.
3. If the answer is NOT present in the context, output: "RISK AUDIT ALERT: Clause not specified in source document." Do NOT hallucinate.

Audit Report:
""")

qa_chain = audit_prompt | llm | StrOutputParser()
print("✅ LLM Auditor Chain Configured Successfully!")

def audit_contract(query: str):
    print("\n" + "="*60)
    print(f"🔍 AUDIT QUERY: {query}")
    print("="*60)

    # 1. Hybrid Search (Dense + Sparse) se top relevant chunks retrieve karna
    retrieved_docs = hybrid_retriever.invoke(query)

    # 2. Context prepare karna with exact page metadata
    context_str = "\n\n".join([
        f"[Source: Page {doc.metadata.get('page', 0) + 1}]:\n" + doc.page_content
        for doc in retrieved_docs
    ])

    # 3. LLM Auditor Chain ko context aur question pass karna
    response = qa_chain.invoke({"context": context_str, "question": query})
    print(response)

# Test 1: Downtime & SLA Penalty Verification
audit_contract("What is the penalty if servers face 1 hour of unapproved downtime?")

# Test 2: Data Compliance & GDPR Clause Check
audit_contract("Where can European customer data be stored and what is the fine for violation?")

# Test 3: Hallucination Guardrail Check (Document me nahi hai yeh info)
audit_contract("What are the working hours of the engineering staff?")

import json

# 1. Custom Agent Tool: Exact SLA Penalty Computation
def calculate_downtime_penalty(hours_down: float, penalty_per_hour: float = 50000.0) -> str:
    """Calculates SLA breach financial penalty based on actual outage duration."""
    total_penalty = max(0.0, hours_down) * penalty_per_hour
    return json.dumps({
        "outage_duration_hours": hours_down,
        "hourly_penalty_rate_usd": penalty_per_hour,
        "total_financial_liability_usd": f"${total_penalty:,.2f}",
        "breach_severity": "CRITICAL" if total_penalty > 100000 else "MODERATE"
    })

# 2. Agent Decision & Execution Flow
def agentic_contract_audit(query: str, observed_downtime_hours: float = None):
    print(f"\n" + "="*60)
    print(f"🤖 AGENT AUDIT INITIATED: {query}")
    print("="*60)

    # Step 1: Retrieval
    docs = hybrid_retriever.invoke(query)
    context_str = "\n".join([d.page_content for d in docs])

    # Step 2: Legal Analysis
    audit_summary = qa_chain.invoke({"context": context_str, "question": query})
    print(f"\n[LEGAL CLAUSE ANALYSIS]:\n{audit_summary}\n")

    # Step 3: Tool Execution (Agentic Decision)
    if observed_downtime_hours is not None:
        print("[AGENT ACTION]: Triggering SLA Financial Risk Engine...")
        risk_data = calculate_downtime_penalty(observed_downtime_hours)
        print(f"[COMPUTED RISK REPORT]:\n{risk_data}")

# Test the Agent with a real outage scenario (e.g., 3.5 hours downtime)
agentic_contract_audit(
    query="What is the hourly outage penalty rate in the contract?",
    observed_downtime_hours=3.5
)

loader = PyPDFLoader("/content/BCN_Campus JD_UG-Intern-Analyst_2026-27 (B.Tech).pdf")

agentic_contract_audit("What are the conditions for contract termination and data protection?", observed_downtime_hours=0)

query_test = "statutory compliance penalty"

print("--- BM25 Results ---")
for doc in bm25_retriever.invoke(query_test):
    print(doc.page_content[:150], "...")

print("\n--- ChromaDB Dense Results ---")
for doc in chroma_retriever.invoke(query_test):
    print(doc.page_content[:150], "...")

def run_system_verification():
    print("🚀 RUNNING PIPELINE VERIFICATION SUITE...\n")

    # -------------------------------------------------------------
    # TEST 1: Grounded Fact Retrieval & Citation Check
    # -------------------------------------------------------------
    q1 = "What is the penalty for unapproved server downtime?"
    docs_1 = hybrid_retriever.invoke(q1)
    context_1 = "\n".join([f"[Page {d.metadata.get('page', 0)+1}]: {d.page_content}" for d in docs_1])
    res_1 = qa_chain.invoke({"context": context_1, "question": q1})

    print("🔹 TEST 1: Factual Retrieval & Citation")
    print(f"Query: '{q1}'")
    print(f"Output:\n{res_1}")

    check_1 = "$50,000" in res_1 and ("Page 2" in res_1 or "Clause 4.2" in res_1)
    print(f"👉 Status: {'✅ PASSED (Accurate Fact + Citation Found)' if check_1 else '❌ FAILED'}\n")
    print("-" * 60)

    # -------------------------------------------------------------
    # TEST 2: Zero-Hallucination Guardrail Check
    # -------------------------------------------------------------
    q2 = "What is the annual employee bonus structure?"
    docs_2 = hybrid_retriever.invoke(q2)
    context_2 = "\n".join([f"[Page {d.metadata.get('page', 0)+1}]: {d.page_content}" for d in docs_2])
    res_2 = qa_chain.invoke({"context": context_2, "question": q2})

    print("🔹 TEST 2: Hallucination Guardrail (Out-of-context query)")
    print(f"Query: '{q2}'")
    print(f"Output:\n{res_2}")

    check_2 = "RISK AUDIT ALERT" in res_2 or "not specified" in res_2.lower() or "not found" in res_2.lower()
    print(f"👉 Status: {'✅ PASSED (Model refused to fabricate answer)' if check_2 else '❌ FAILED'}\n")
    print("-" * 60)

    # -------------------------------------------------------------
    # TEST 3: Dynamic Agent Tool Execution
    # -------------------------------------------------------------
    hours = 3.5
    raw_tool_output = calculate_downtime_penalty(hours)

    print("🔹 TEST 3: SLA Penalty Risk Engine Calculation")
    print(f"Input Outage: {hours} hours (Expected: $175,000.00)")
    print(f"Tool Output:\n{raw_tool_output}")

    check_3 = "$175,000.00" in raw_tool_output and "CRITICAL" in raw_tool_output
    print(f"👉 Status: {'✅ PASSED (Math and logic verified)' if check_3 else '❌ FAILED'}\n")

run_system_verification()

# Direct overall summary lene ke liye:
agentic_contract_audit(
    query="Provide a concise executive summary of this entire document, highlighting the main business problem and top 3 findings."
)
